### ISSUE TITLE
add pre-commit lint check git hook

### ISSUE THREAD

**Issue by plastikfan** [snivilised/cobrass#73]

**Comment by plastikfan** [comment]
the linter `gocritic` panics for some reason so it has been disabled:

```
 plastikfan@Janus  ~/dev/github/go/snivilised/cobrass λ   chore/add-lint-pre-commit-hook  task lint
WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
ERRO [runner] Panic: gocritic: package "l10n" (isInitialPkg: true, needAnalyzeSource: true): unreachable: goroutine 4083 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/goanalysis/runner_action.go:101 +0x155
panic({0x144b540, 0x1868560})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/go-critic/go-critic/checkers.(*typeDefFirstChecker).receiverType(0x14b8680?, {0x18734e8?, 0xc0051044e0?})
        /home/plastikfan/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/typeDefFirst_checker.go:82 +0x8f
github.com/go-critic/go-critic/checkers.(*typeDefFirstChecker).walkDecl(0xc00aaef4b8, {0x1873338?, 0xc005104660?})
        /home/plastikfan/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/typeDefFirst_checker.go:55 +0xc5
github.com/go-critic/go-critic/checkers.(*typeDefFirstChecker).WalkFile(0xc00aaef4b8, 0xc0049e1600)
        /home/plastikfan/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/checkers/typeDefFirst_checker.go:44 +0xac
github.com/go-critic/go-critic/framework/linter.(*Checker).Check(...)
        /home/plastikfan/go/pkg/mod/github.com/go-critic/go-critic@v0.6.3/framework/linter/linter.go:129
github.com/golangci/golangci-lint/pkg/golinters.runGocriticOnFile(0xc00512a6c0, 0xc000c0c76e?, {0xc000435400, 0x68, 0xc000137130?})
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/gocritic.go:138 +0xcc
github.com/golangci/golangci-lint/pkg/golinters.runGocriticOnPackage(0xc00512a6c0, {0xc000435400, 0x68, 0x80}, {0xc00012f7f0, 0x1, 0x0?})
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/gocritic.go:126 +0x1df
github.com/golangci/golangci-lint/pkg/golinters.goCriticWrapper.run({0xc0006b4388?, 0xc0006b4000?, {0x18739f8?, 0xc000137130?}}, 0xc0051172b0)
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/gocritic.go:86 +0x231
github.com/golangci/golangci-lint/pkg/golinters.NewGocritic.func1(0x14b0520?)
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/gocritic.go:41 +0x45
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc001a8a620)
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/goanalysis/runner_action.go:187 +0x9c4
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/goanalysis/runner_action.go:105 +0x1d
github.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc000597b80, {0x16114f7, 0x8}, 0xc001d92748)
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/timeutils/stopwatch.go:111 +0x4a
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc00091c960?)
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/goanalysis/runner_action.go:104 +0x85
github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc001a8a620)
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xb4
created by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze
        /home/plastikfan/go/pkg/mod/github.com/golangci/golangci-lint@v1.47.2/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x1eb
WARN [runner] Can't run linter goanalysis_metalinter: goanalysis_metalinter: gocritic: package "l10n" (isInitialPkg: true, needAnalyzeSource: true): unreachable
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] tparallel is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
ERRO Running error: 1 error occurred:
        * can't run linter goanalysis_metalinter: goanalysis_metalinter: gocritic: package "l10n" (isInitialPkg: true, needAnalyzeSource: true): unreachable

task: Failed to run task "lint": exit status 3
 ✘ plastikfan@Janus  ~/dev/github/go/snivilised/cobrass λ   chore/add-lint-pre-commit-hook
```

**Comment by plastikfan** [comment]
Some of the linting is too aggressive and is out of sync with the git hook. So abandon this, except to apply the linting fixes that weren't too onerous.
